### ISSUE TITLE
大佬这个机器人该咋配置啊

### ISSUE THREAD

**Issue by wangmengen1** [chr233/ASFBuffBot#1]
![image](https://github.com/chr233/ASFBuffBot/assets/96656026/0e1e2fd8-b592-4c67-9c3e-48100698c683)

**Comment by chr233** [comment]
dll 有没有丢进 plugins 目录

**Comment by wangmengen1** [comment]
![image](https://github.com/chr233/ASFBuffBot/assets/96656026/7af1d8f3-c353-4fd5-b49d-7a8daa0230d0)
没有这个目录啊
