### ISSUE TITLE
绑定了手机号的buff账号需要验证

### ISSUE THREAD

**Issue by Megalounge** [chr233/ASFBuffBot#2]
打开官网使用steam登录就会出现类似提示 需要输入手机验证码才可继续
![截图](https://github.com/chr233/ASFBuffBot/assets/54276184/b9d35ccf-b790-40f3-9651-6208d92476d8)
![QQ截图](https://github.com/chr233/ASFBuffBot/assets/54276184/c06c85e0-2068-4829-a06d-eb3fa443ebc8)

**Comment by chr233** [comment]
下个版本会增加验证码功能

**Comment by chr233** [comment]
已更新 1.1.0.0
